{
  "title": "OpenHands Deployment Script",
  "description": "Automated deployment script for OpenHands with Docker support and environment configuration.",
  "author": "Infrastructure Team",
  "category": "scripts",
  "tags": ["deployment", "docker", "automation", "bash"],
  "createdAt": "2024-01-08T14:20:00Z",
  "updatedAt": "2024-01-25T10:15:00Z",
  "code": "#!/bin/bash\n\n# OpenHands Deployment Script\n# Automates the deployment of OpenHands with Docker\n\nset -e\n\n# Configuration\nOPENHANDS_VERSION=\"latest\"\nCONTAINER_NAME=\"openhands-app\"\nPORT=\"3000\"\nENV_FILE=\".env\"\n\n# Colors for output\nRED='\\033[0;31m'\nGREEN='\\033[0;32m'\nYELLOW='\\033[1;33m'\nNC='\\033[0m' # No Color\n\nlog_info() {\n    echo -e \"${GREEN}[INFO]${NC} $1\"\n}\n\nlog_warn() {\n    echo -e \"${YELLOW}[WARN]${NC} $1\"\n}\n\nlog_error() {\n    echo -e \"${RED}[ERROR]${NC} $1\"\n}\n\n# Check if Docker is installed\nif ! command -v docker &> /dev/null; then\n    log_error \"Docker is not installed. Please install Docker first.\"\n    exit 1\nfi\n\n# Check if environment file exists\nif [[ ! -f \"$ENV_FILE\" ]]; then\n    log_warn \"Environment file $ENV_FILE not found. Creating default...\"\n    cat > \"$ENV_FILE\" << EOF\n# OpenHands Configuration\nOPENAI_API_KEY=your_openai_api_key_here\nANTHROPIC_API_KEY=your_anthropic_api_key_here\nWORKSPACE_BASE=/opt/workspace_base\nEOF\n    log_info \"Please edit $ENV_FILE with your API keys before running again.\"\n    exit 1\nfi\n\n# Stop existing container if running\nif docker ps -q -f name=\"$CONTAINER_NAME\" | grep -q .; then\n    log_info \"Stopping existing container...\"\n    docker stop \"$CONTAINER_NAME\"\n    docker rm \"$CONTAINER_NAME\"\nfi\n\n# Pull latest image\nlog_info \"Pulling OpenHands image...\"\ndocker pull \"ghcr.io/all-hands-ai/openhands:$OPENHANDS_VERSION\"\n\n# Run container\nlog_info \"Starting OpenHands container...\"\ndocker run -d \\\n    --name \"$CONTAINER_NAME\" \\\n    --env-file \"$ENV_FILE\" \\\n    -p \"$PORT:3000\" \\\n    -v /var/run/docker.sock:/var/run/docker.sock \\\n    -v \"$(pwd)/workspace:/opt/workspace_base\" \\\n    \"ghcr.io/all-hands-ai/openhands:$OPENHANDS_VERSION\"\n\nlog_info \"OpenHands deployed successfully!\"\nlog_info \"Access it at: http://localhost:$PORT\"\nlog_info \"Container name: $CONTAINER_NAME\"\n\n# Show logs\nlog_info \"Showing container logs (Ctrl+C to exit):\"\ndocker logs -f \"$CONTAINER_NAME\""
}